apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: go-simple-webserver
  labels:
    app: go-simple-webserver
spec:
  replicas: 10
  strategy:
    canary:
      steps:
        - setWeight: 25
        - pause: { duration: 120s }
        - setWeight: 75
        - pause: { duration: 120s }
        - setWeight: 100
        - pause: { duration: 120s }
  selector:
    matchLabels:
      app: go-simple-webserver
  template:
    metadata:
      labels:
        app: go-simple-webserver
    spec:
      containers:
        - name: webserver
          image: ghcr.io/iuniod/ci_cd_lab@sha256:049c05d0cdc9945dc29e9f8bdc76d23cde4bf4ba33a7b0e2f0b75fc39f2508e8
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
